name: cibuildwheel

on:
  push:
    paths: #Condition to go ahead
      - "**.py"
      - "**.f90"
      - "**.f"
      - .github/workflows/cibuildwheel.yml

jobs:
  
  tests:
    name: Test build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest] ####[ubuntu-latest, windows-latest] ### windows-latest, , something wrong with windows and macos
        fortran-compiler: [gfortran-9] # Version of GFortran we want to use.
        python_version: ['3.8']
    env:
      FC: ${{ matrix.fortran-compiler }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Used to host cibuildwheel
      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
          python-version: ${{ matrix.python_version }}    

      - name: Set up numpy
        run: python -m pip install numpy
    
      - name: Install GFortran Linux
        if: contains(matrix.os, 'ubuntu')
        run: sudo apt-get install ${{matrix.fortran-compiler}}
          
      - name: Install GFortran macOS
        if: contains(matrix.os, 'macos')
        ##run: brew install gcc@9
        run: pip install -e .
    
    ##  - name: Build f2py
    ##    run: f2py -c src/mask_interpolation.f90 -m mask_interpolation --f90flags='-fopenmp' -lgomp
        
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.0.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
