name: cibuildwheel

on:
  push:
    paths: #Condition to go ahead
      - "**.py"
      - "**.f90"
      - "**.f"
      - .github/workflows/cibuildwheel.yml

jobs:
  
  tests:
    name: Test build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest,ubuntu-latest]
        fortran-compiler: [gfortran] # Version of GFortran we want to use.
        python_version: ['3.8']
    env:
      FC: ${{ matrix.fortran-compiler }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Used to host cibuildwheel
      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
          python-version: ${{ matrix.python_version }}    

      - name: Set up numpy
        run: python -m pip install numpy
    
      - name: Install GFortran Linux
        if: contains(matrix.os, 'ubuntu')
        run: sudo apt-get install ${{ matrix.fortran-compiler}}
    
      - name: Install GFortran macOS
        if: contains(matrix.os, 'macos')
    
      - name: Build
        run: f2py -c -m src/mask_interpolation.f90 mask_interpolation
        
