name: Documentation

on:
  push:
    branches:
      - main         # Push events on main branch
    paths: #Condition to go ahead
      - .github/workflows/document.yml
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install Sphinx
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx_rtd_theme
        pip install -e .
    - name: Generate documentation
      working-directory: docs
      run: make html
